name: Feature request
description: Propose an idea for a feature or an enhancement
labels: [enhancement]
type: Feature
body:
  - type: textarea
    attributes:
      label: What feature are you requesting?
      description: Please describe what feature you want to have in Form Block in an upcoming version.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Why is this feature necessary?
      description: Please provide information why your requested feature improves Form Block.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Are you expecing side-effects?
      description: When adding your feature, can you see any side-effects that may occur during/after the implementation?
    validations:
      required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/epiphyt/embed-privacy/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
    validations:
      required: false
