import { applyFilters } from '@wordpress/hooks';
import { __ } from '@wordpress/i18n';

export const getAllowedAttributes = ( type ) => {
	return types[ type ].allowedAttributes;
};

export const getTypes = () => Object.keys( types );

export const isAllowedAttribute = ( type, attribute ) => {
	if ( ! types[ type ] ) {
		return false;
	}

	return types[ type ].allowedAttributes.includes( attribute );
};

export const types = applyFilters( 'formBlock.input.htmlTypes', {
	checkbox: {
		allowedAttributes: [
			'checked',
			'disabled',
			'label',
			'required',
			'value',
		],
		label: __( 'Checkbox', 'form-block' ),
	},
	color: {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'disabled',
			'label',
		],
		label: __( 'Color selection', 'form-block' ),
	},
	date: {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'disabled',
			'label',
			'max',
			'min',
			'readOnly',
			'required',
			'spellCheck',
			'step',
		],
		label: __( 'Date', 'form-block' ),
	},
	'date-custom': {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'customDate',
			'disabled',
			'label',
			'readOnly',
			'required',
			'spellCheck',
		],
		label: __( 'Date with separate fields', 'form-block' ),
	},
	'datetime-local': {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'disabled',
			'label',
			'max',
			'min',
			'readOnly',
			'required',
			'spellCheck',
			'step',
		],
		label: __( 'Date and time', 'form-block' ),
	},
	'datetime-local-custom': {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'customDate',
			'disabled',
			'label',
			'readOnly',
			'required',
			'spellCheck',
		],
		label: __( 'Date and time with separate fields', 'form-block' ),
	},
	email: {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'disabled',
			'isReplyTo',
			'label',
			'maxLength',
			'minLength',
			'multiple',
			'pattern',
			'placeholder',
			'readOnly',
			'required',
			'size',
			'spellCheck',
		],
		label: __( 'E-mail', 'form-block' ),
	},
	file: {
		allowedAttributes: [
			'accept',
			'autoComplete',
			'autoCompleteSection',
			'capture',
			'disabled',
			'dropzone',
			'label',
			'localFiles',
			'multiple',
			'readOnly',
			'required',
		],
		label: __( 'File', 'form-block' ),
	},
	hidden: {
		allowedAttributes: [ 'value' ],
		label: __( 'Hidden', 'form-block' ),
	},
	image: {
		allowedAttributes: [
			'alt',
			'autoComplete',
			'autoCompleteSection',
			'disabled',
			'height',
			'label',
			'readOnly',
			'required',
			'src',
			'width',
		],
		label: __( 'Image', 'form-block' ),
	},
	month: {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'disabled',
			'label',
			'max',
			'min',
			'readOnly',
			'required',
			'spellCheck',
			'step',
		],
		label: __( 'Month', 'form-block' ),
	},
	'month-custom': {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'customDate',
			'disabled',
			'label',
			'readOnly',
			'required',
			'spellCheck',
		],
		label: __( 'Month with separate fields', 'form-block' ),
	},
	number: {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'disabled',
			'label',
			'max',
			'min',
			'placeholder',
			'readOnly',
			'required',
			'spellCheck',
			'step',
		],
		label: __( 'Number', 'form-block' ),
	},
	password: {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'disabled',
			'label',
			'maxLength',
			'minLength',
			'pattern',
			'placeholder',
			'readOnly',
			'required',
			'size',
		],
		label: __( 'Password (input not visible)', 'form-block' ),
	},
	radio: {
		allowedAttributes: [
			'checked',
			'disabled',
			'label',
			'required',
			'value',
		],
		label: __( 'Radio button', 'form-block' ),
	},
	range: {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'disabled',
			'label',
			'max',
			'min',
			'step',
		],
		label: __( 'Range', 'form-block' ),
	},
	reset: {
		allowedAttributes: [ 'disabled', 'value' ],
		label: __( 'Reset button', 'form-block' ),
	},
	search: {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'dirname',
			'disabled',
			'label',
			'maxLength',
			'minLength',
			'pattern',
			'placeholder',
			'readOnly',
			'required',
			'size',
			'spellCheck',
		],
		label: __( 'Search', 'form-block' ),
	},
	submit: {
		allowedAttributes: [ 'disabled', 'value' ],
		label: __( 'Submit button', 'form-block' ),
	},
	tel: {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'disabled',
			'label',
			'maxLength',
			'minLength',
			'pattern',
			'placeholder',
			'readOnly',
			'required',
			'size',
			'spellCheck',
		],
		label: __( 'Telephone', 'form-block' ),
	},
	text: {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'dirname',
			'disabled',
			'label',
			'maxLength',
			'minLength',
			'pattern',
			'placeholder',
			'readOnly',
			'required',
			'size',
			'spellCheck',
		],
		label: __( 'Text', 'form-block' ),
	},
	time: {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'disabled',
			'label',
			'max',
			'min',
			'readOnly',
			'required',
			'spellCheck',
			'step',
		],
		label: __( 'Time', 'form-block' ),
	},
	'time-custom': {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'customDate',
			'disabled',
			'label',
			'readOnly',
			'required',
			'spellCheck',
		],
		label: __( 'Time with separate fields', 'form-block' ),
	},
	url: {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'disabled',
			'label',
			'maxLength',
			'minLength',
			'pattern',
			'placeholder',
			'readOnly',
			'required',
			'size',
			'spellCheck',
		],
		label: __( 'URL', 'form-block' ),
	},
	week: {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'disabled',
			'label',
			'max',
			'min',
			'readOnly',
			'required',
			'spellCheck',
			'step',
		],
		label: __( 'Week', 'form-block' ),
	},
	'week-custom': {
		allowedAttributes: [
			'autoComplete',
			'autoCompleteSection',
			'customDate',
			'disabled',
			'label',
			'readOnly',
			'required',
			'spellCheck',
		],
		label: __( 'Week with separate fields', 'form-block' ),
	},
} );
